- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Download Google Chrome
    command: sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
  - name: Install Google Chrome
    command: sudo apt-get -y install google-chrome-stable
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/EdurekaProject.git dest=~/devops21
  - name: build the dockerfile
    command: chdir=~/devops21 docker build -t devopsproject2021:successful .
  - name: create container
    command: docker run -itd -p 8989:80 devopsproject2021:successful
