- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install nginx
    yum: name=tomcat state=present
  - name: start nginx
    service: name=tomcat state=started
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/EdurekaProject.git dest=~/edurekaproject21
  - name: build the dockerfile
    command: chdir=~/ build -t jsdhekale/edurekaproject21:new .
  - name: login docker
    command: docker login --username jsdhekale --password Edureka@21
  - name: tag the image
    command: docker tag jsdhekale/edurekaproject21:new edurekaproject21:v2 
  - name: push
    command: docker push edurekaproject21:v2
  - name: create container
    command: docker run -itd -P edurekaproject21:v2
