- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/AnsibleDockerdemo.git dest=/tmp/gitrepo
  - name: build the dockerfile
    command: chdir=/tmp/gitrepo build -t myimage:ansible17 .
  - name: Run the image to deploy the app
    command: docker run -itd -p myimage:ansible17
