- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/EdurekaProject.git dest=~/edurekaproject21
  - name: build the dockerfile
    command: chdir=~/edurekaproject21 docker build -t edurekaproject21 .
 
