- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/EdurekaProject.git dest=~/devops
  - name: build the dockerfile
    command: chdir=~/devops docker build -t edurekaproject2021:successful .
  - name: create container
    command: sudo docker run -itd -P edurekaproject2021:successful:$BUILD_NUMBER 
