- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: docker pull nginx
    yum: name=ngnix state=present
  - name: docker start nginx
    service: name=nginx state=started
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/EdurekaProject.git dest=~/edurekaproject21
  - name: build the dockerfile
    command: chdir=~/edurekaproject21 docker build -t edurekaproject21 .
  - name: login docker
    command: docker login --username jsdhekale --password Edureka@21
  - name: tag the image
    command: docker tag edurekaproject21 edurekaproject21:v2 
  - name: push
    command: docker push jsdhekale/edurekaproject21:v2
  - name: create container
    command: docker run -itd -P edurekaproject21
