- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install jdk
    command: wget http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm  dest:/opt/jdk-8u60-linux-x64.rpm
  - name: Install Java JDK rpm from a local file
    command: yum /opt/jdk-8u60-linux-x64.rpm
  - name: Download Chrome Driver
    command: sudo wget https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
  - name: Unzip Chrome Driver 
    command: sudo unzip chromedriver_linux64.zip
  - name: Mv Chrome Driver
    command: sudo mv chromedriver /usr/bin/chromedriver
  - name: Install Chrome Browser
    command: sudo curl https://intoli.com/install-google-chrome.sh | bash
  - name: Mv Google Chrome
    command: sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome 
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/EdurekaProject.git dest=~/devops21
  - name: build the dockerfile
    command: chdir=~/devops21 docker build -t devopsproject2021:successful .
  - name: create container
    command: docker run -itd -p 8989:80 devopsproject2021:successful
