- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/EdurekaProject.git dest=~/devopsproject2021
  - name: build the dockerfile
    command: chdir=~/devopsproject2021 docker build -t devopsproject2021:successful .
  - name: create container
    command: docker run -itd -p 8686:80 devopsproject2021:successful
