- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install git & docker
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: start docker
    service: name=docker state=started
  - name: clone my repo
    git: repo=https://github.com/jsdhekale/EdurekaProject.git dest=~/devops21
  - name: build the dockerfile
    command: chdir=~/devops21 docker build -t devopsproject2022:successful .
  - name: create container
    command: docker run -itd devopsproject2022:successful
